- name: Make sure Python2 is available
  hosts: ldap
  become: True
  gather_facts: False
  tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- name: Install OpenLDAP
  hosts: ldap
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - openldap_server
    - { role: lam, when: lam.enabled == True }

  handlers:

  - name: restart slapd
    service: name=slapd state=restarted enabled=yes
